//>>built
define("esri/layers/LabelLayer","require dojo/_base/declare dojo/_base/lang dojo/number dojo/i18n!dojo/cldr/nls/number dojo/_base/array dojo/_base/connect dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ../geometry/webMercatorUtils ./GraphicsLayer ./LabelClass ../renderers/SimpleRenderer ../renderers/arcadeUtils".split(" "),
function(n,B,m,C,x,y,s,D,z,E,t,F,G,H,I,p,u,J,K,A,L,v,M,w){function N(a){return"sizeInfo"===a.type}n=B(L,{declaredClass:"esri.layers.LabelLayer",constructor:function(a){this._refreshLabels=m.hitch(this,this._refreshLabels);this.id="labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){this._mapEventHandlers.push(a.on("extent-change",
m.hitch(this,"_handleLevelChange")));var b=this.inherited(arguments);this.refresh();return b},_unsetMap:function(){var a;for(a=0;a<this._mapEventHandlers.length;a++)s.disconnect(this._mapEventHandlers[a]);this.refresh();clearTimeout(this._refreshHandle);this._refreshHandle=null;this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,b,c,h){if(!this.getFeatureLayer(a.layerId)){var k=[];k.push(a.on("update-end",
m.hitch(this,"refresh")));k.push(a.on("suspend",m.hitch(this,"refresh")));k.push(a.on("resume",m.hitch(this,"refresh")));k.push(a.on("edits-complete",m.hitch(this,"refresh")));k.push(a.on("labeling-info-change",m.hitch(this,"refresh")));k.push(a.on("time-extent-change",m.hitch(this,"refresh")));k.push(a.on("show-labels-change",m.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:c,LabelingOptions:h,LabelRenderer:b,EventHandlers:k});this.featureLayers.push(a);
this.refresh()}},getFeatureLayer:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return c;return null},removeFeatureLayer:function(a){var b;a=this.getFeatureLayer(a);if(void 0!==a&&(b=y.indexOf(this.featureLayers,a),-1<b)){this.featureLayers.splice(b,1);for(a=0;a<this._featureLayerInfos[b].EventHandlers.length;a++)s.disconnect(this._featureLayerInfos[b].EventHandlers[a]);this._featureLayerInfos.splice(b,1);this.refresh()}},removeAllFeatureLayers:function(){var a;
for(a=0;a<this.featureLayers.length;a++){for(var b=0;b<this._featureLayerInfos[a].EventHandlers.length;b++)s.disconnect(this._featureLayerInfos[a].EventHandlers[b]);this.featureLayers=[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},getFeatureLayerInfo:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return this._featureLayerInfos[b];return null},refresh:function(){null==this._refreshHandle&&
(this._refreshHandle=setTimeout(this._refreshLabels,0))},_handleLevelChange:function(a){a.levelChange&&this.clear();this.refresh()},_refreshLabels:function(a){this._refreshHandle=null;var b,c,h,k,d,f=[],e,g="DYNAMIC"===this._engineType?new H:new I;if(this._map){g.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(c=this.featureLayers[a],c.visible&&c.showLabels&&c.visibleAtMapScale&&!c._suspended)if(b=this._featureLayerInfos[a],d=this._convertOptions(null),b.LabelRenderer){if(f=
c.labelingInfo)if(e=f[0])k=this._getLabelExpression(e),d=this._convertOptions(e);h=b.LabelRenderer;b.LabelExpressionInfo&&(k=b.LabelExpressionInfo);b.LabelingOptions&&(d=this._convertOptions(null),void 0!==b.LabelingOptions.pointPriorities&&(f=b.LabelingOptions.pointPriorities,d.pointPriorities="above-center"==f||"AboveCenter"==f||"esriServerPointLabelPlacementAboveCenter"==f?"AboveCenter":"above-left"==f||"AboveLeft"==f||"esriServerPointLabelPlacementAboveLeft"==f?"AboveLeft":"above-right"==f||"AboveRight"==
f||"esriServerPointLabelPlacementAboveRight"==f?"AboveRight":"below-center"==f||"BelowCenter"==f||"esriServerPointLabelPlacementBelowCenter"==f?"BelowCenter":"below-left"==f||"BelowLeft"==f||"esriServerPointLabelPlacementBelowLeft"==f?"BelowLeft":"below-right"==f||"BelowRight"==f||"esriServerPointLabelPlacementBelowRight"==f?"BelowRight":"center-center"==f||"CenterCenter"==f||"esriServerPointLabelPlacementCenterCenter"==f?"CenterCenter":"center-left"==f||"CenterLeft"==f||"esriServerPointLabelPlacementCenterLeft"==
f?"CenterLeft":"center-right"==f||"CenterRight"==f||"esriServerPointLabelPlacementCenterRight"==f?"CenterRight":"AboveRight"),void 0!==b.LabelingOptions.lineLabelPlacement&&(d.lineLabelPlacement=b.LabelingOptions.lineLabelPlacement),void 0!==b.LabelingOptions.lineLabelPosition&&(d.lineLabelPosition=b.LabelingOptions.lineLabelPosition),void 0!==b.LabelingOptions.labelRotation&&(d.labelRotation=b.LabelingOptions.labelRotation),void 0!==b.LabelingOptions.howManyLabels&&(d.howManyLabels=b.LabelingOptions.howManyLabels));
h instanceof v&&(k=this._getLabelExpression(h),h=new M(h.symbol),d=this._convertOptions(h));this._addLabels(c,h,k,d)}else if(f=c.labelingInfo)for(b=f.length-1;0<=b;b--)if(e=f[b])h=new v(e instanceof v?e.toJson():e),k=this._getLabelExpression(e),d=this._convertOptions(e),this._addLabels(c,h,k,d);k=g._process(this._preparedLabels);this.clear();this.drawLabels(this._map,k)}},drawLabels:function(a,b){this._scale=(a.extent.xmax-a.extent.xmin)/a.width;var c;for(c=0;c<b.length;c++){var h=b[c],k=h.x,d=h.y,
f=h.text,e=h.angle,g=h.layer.labelSymbol;"polyline"==h.layer.geometry.type&&h.layer.options.labelRotation&&g.setAngle(e*(180/Math.PI));g.setText(f);h=k;g instanceof p&&(k=g.getHeight(),e=Math.sin(e),h-=0.25*k*this._scale*e,d-=0.33*k*this._scale);e=new F(new K(h,d,a.extent.spatialReference));e.setSymbol(g);this.add(e)}},_addLabels:function(a,b,c,h){var k,d,f,e;if(this._isWithinScaleRange(b.minScale,b.maxScale)&&c&&""!==c){var g=this._map,l=!a.url&&!g.spatialReference.equals(a.spatialReference);for(k=
0;k<a.graphics.length;k++)if(d=a.graphics[k],!1!==d.visible){f=d.geometry;if(l){if(!A.canProject(f,g))continue;f=A.project(f,g)}f&&(this._isWhere(b.where,d.attributes)&&this._isWithinScreenArea(f))&&(e=this._buildLabelText(c,d,a.fields,h),this._addLabel(e,b,a.renderer,d,h,f,g))}}},_isWithinScreenArea:function(a){a="point"===a.type?new J(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();if(void 0===a)return!1;a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,
b){var c=this._map.getScale();return 0<a&&c>=a||0<b&&c<=b?!1:!0},_isWhere:function(a,b){try{if(!a)return!0;if(a){var c=a.split(" ");if(3===c.length)return this._sqlEquation(b[this._removeQuotes(c[0])],c[1],this._removeQuotes(c[2]));if(7===c.length){var h=this._sqlEquation(b[this._removeQuotes(c[0])],c[1],this._removeQuotes(c[2])),k=c[3],d=this._sqlEquation(b[this._removeQuotes(c[4])],c[5],this._removeQuotes(c[6]));switch(k){case "AND":return h&&d;case "OR":return h||d}}}return!1}catch(f){}},_sqlEquation:function(a,
b,c){switch(b){case "\x3d":return a==c?!0:!1;case "\x3c\x3e":return a!=c?!0:!1;case "\x3e":return a>c?!0:!1;case "\x3e\x3d":return a>=c?!0:!1;case "\x3c":return a<c?!0:!1;case "\x3c\x3d":return a<=c?!0:!1}return!1},_removeQuotes:function(a){var b=a.indexOf('"'),c=a.lastIndexOf('"');if(-1!=b&&-1!=c)return a.substr(1,a.length-2);b=a.indexOf("'");c=a.lastIndexOf("'");return-1!=b&&-1!=c?a.substr(1,a.length-2):a},_getSizeInfo:function(a){return a?a.sizeInfo||y.filter(a.visualVariables,N)[0]:null},_addLabel:function(a,
b,c,h,k,d,f){var e,g,l,q;if(a&&""!==m.trim(a)&&b){a=a.replace(/\s+/g," ");e=b.getSymbol(h);e instanceof p?(e=new p(e.toJson()),e.setVerticalAlignment("baseline"),e.setHorizontalAlignment("center")):e=e instanceof u?new u(e.toJson()):new p;e.setText(a);b.symbol=e;if(l=this._getProportionalSize(b.sizeInfo,h.attributes))e instanceof p?e.setSize(l):e instanceof u&&(e.setWidth(l),e.setHeight(l));q=l=0;if(c){g=c.getSymbol(h);var n=this._getSizeInfo(c),r;n&&(r=c.getSize(h,{sizeInfo:n,resolution:f.getResolutionInMeters()}));
if(r&&null!==r)l=q=r;else if(g)if("simplemarkersymbol"==g.type)q=l=g.size;else if("picturemarkersymbol"==g.type)l=g.width,q=g.height;else if("simplelinesymbol"==g.type||"cartographiclinesymbol"==g.type)l=g.width}c={};c.graphic=h;c.options=k;c.geometry=d;c.labelRenderer=b;c.labelSymbol=e;c.labelWidth=e.getWidth()/2;c.labelHeight=e.getHeight()/2;c.symbolWidth=z.normalizedLength(l)/2;c.symbolHeight=z.normalizedLength(q)/2;c.text=a;c.angle=e.angle;this._preparedLabels.push(c)}},_buildLabelText:function(a,
b,c,h){if(h.hasExpression)return a=w.executeFunction(h.compiledFunc,w.createExecContext(b,b._getView())),t.isDefined(a)?""+a:"";var k=b.attributes;return a.replace(/{[^}]*}/g,function(a){var b,e=a;for(b=0;b<c.length;b++)if("{"+c[b].name+"}"==a){var e=k[c[b].name],g=c[b].domain;if(g&&m.isObject(g)){if("codedValue"==g.type&&h.useCodedValues){b=e;for(a=0;a<g.codedValues.length;a++)if(g.codedValues[a].code==b){e=g.codedValues[a].name;break}}else"range"==g.type&&(g.minValue<=e&&e<=g.maxValue)&&(e=g.name);
break}g=c[b].type;if(h.fieldInfos){var l=h.fieldInfos;for(b=0;b<l.length;b++)if("{"+l[b].fieldName+"}"==a){a=l[b].format;if("esriFieldTypeDate"==g)(a="DateFormat"+G.prototype._dateFormats[a.dateFormat?a.dateFormat:"shortDate"])&&(e=t.substitute({myKey:e},"${myKey:"+a+"}"));else if(("esriFieldTypeInteger"==g||"esriFieldTypeSingle"==g||"esriFieldTypeSmallInteger"==g||"esriFieldTypeLong"==g||"esriFieldTypeDouble"==g)&&a)e=C.format(e,{places:a.places}),a.digitSeparator||x.group&&(e=e.replace(RegExp("\\"+
x.group,"g"),""));break}}break}else e="";return null===e?"":e})},_getLabelExpression:function(a){var b="";a.labelExpressionInfo?b=a.labelExpressionInfo.value||a.labelExpressionInfo.expression:this._validSyntax(a.labelExpression)&&(b=this._convertLabelExpression(a.labelExpression));return b},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(RegExp("\\[","g"),"{").replace(RegExp("\\]","g"),"}")},_getProportionalSize:function(a,b){if(!a)return null;
var c=t.substitute(b,"${"+a.field+"}",{first:!0});return!a.minSize||!a.maxSize||!a.minDataValue||!a.maxDataValue||!c||0>=a.maxDataValue-a.minDataValue?null:(a.maxSize-a.minSize)/(a.maxDataValue-a.minDataValue)*(c-a.minDataValue)+a.minSize},_convertOptions:function(a){var b=!0,c="shortDate",h=null,k=null,d="",f=!0,e,g;if(a&&(a.format&&(c=a.format.dateFormat,h={places:a.format.places,digitSeparator:a.format.digitSeparator}),k=a.fieldInfos,d=a.labelPlacement,null!=a.useCodedValues&&(b=a.useCodedValues),
a=a.labelExpressionInfo)){var l=a.expression;l&&!a.value&&(g=!0,e=w.createFunction(l))}if("always-horizontal"==d||"esriServerPolygonPlacementAlwaysHorizontal"==d)f=!1;return{useCodedValues:b,dateFormat:c,numberFormat:h,fieldInfos:k,pointPriorities:"above-center"==d||"esriServerPointLabelPlacementAboveCenter"==d?"AboveCenter":"above-left"==d||"esriServerPointLabelPlacementAboveLeft"==d?"AboveLeft":"above-right"==d||"esriServerPointLabelPlacementAboveRight"==d?"AboveRight":"below-center"==d||"esriServerPointLabelPlacementBelowCenter"==
d?"BelowCenter":"below-left"==d||"esriServerPointLabelPlacementBelowLeft"==d?"BelowLeft":"below-right"==d||"esriServerPointLabelPlacementBelowRight"==d?"BelowRight":"center-center"==d||"esriServerPointLabelPlacementCenterCenter"==d?"CenterCenter":"center-left"==d||"esriServerPointLabelPlacementCenterLeft"==d?"CenterLeft":"center-right"==d||"esriServerPointLabelPlacementCenterRight"==d?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==d||"below-start"==d||"center-start"==d?"PlaceAtStart":
"above-end"==d||"below-end"==d||"center-end"==d?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==d||"esriServerLinePlacementAboveAfter"==d||"above-along"==d||"esriServerLinePlacementAboveAlong"==d||"above-before"==d||"esriServerLinePlacementAboveBefore"==d||"above-start"==d||"esriServerLinePlacementAboveStart"==d||"above-end"==d||"esriServerLinePlacementAboveEnd"==d?"Above":"below-after"==d||"esriServerLinePlacementBelowAfter"==d||"below-along"==d||"esriServerLinePlacementBelowAlong"==
d||"below-before"==d||"esriServerLinePlacementBelowBefore"==d||"below-start"==d||"esriServerLinePlacementBelowStart"==d||"below-end"==d||"esriServerLinePlacementBelowEnd"==d?"Below":"center-after"==d||"esriServerLinePlacementCenterAfter"==d||"center-along"==d||"esriServerLinePlacementCenterAlong"==d||"center-before"==d||"esriServerLinePlacementCenterBefore"==d||"center-start"==d||"esriServerLinePlacementCenterStart"==d||"center-end"==d||"esriServerLinePlacementCenterEnd"==d?"OnLine":"Above",labelRotation:f,
howManyLabels:"OneLabel",hasExpression:g,compiledFunc:e}}});D("extend-esri")&&m.setObject("layers.LabelLayer",n,E);return n});