//>>built
define("esri/dijit/metadata/base/xml/XmlImporter","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../etc/docUtil ../etc/matchTopNodeUtil ./XmlFlattener ./xmlUtil ../../../../kernel dojo/sniff".split(" "),function(l,m,g,n,r,p,s,k,q){l=l(null,{constructor:function(b){m.mixin(this,b)},importDocument:function(b,a,c){var d=b.rootElement;b={asTemplate:c,considerGML3andGML32:!0,gxeDocument:b,xmlDocument:a,gxeData:{nsUrisByPrefix:k.makeGxeUrisByPrefix(b.getNamespaces()),nsPrefixesByUri:k.makeGxePrefixesByUri(b.getNamespaces())}};
this._walk(b,d,null)},_findMatchingDomAttribute:function(b,a,c){var d=null;g.some(c.attributes,function(c){if(this._isMatching(b,a,c))return d=c,!0},this);return d},_findMatchingDomElements:function(b,a,c){var d=null,e=k.nodeTypes.ELEMENT_NODE;g.forEach(c.childNodes,function(c){c.nodeType===e&&this._isMatching(b,a,c)&&(null===d&&(d=[]),d.push(c))},this);return d},_findMatchingSubTarget:function(b,a,c){var d=null,e=k.nodeTypes.ELEMENT_NODE;g.some(c.childNodes,function(c){if(c.nodeType===e)if("TopicCatCd@value"===
a){if(this._isMatching(b,"TopicCatCd",c)&&g.some(c.attributes,function(a){if(this._isMatching(b,"value",a))return d=a,!0},this))return!0}else if(this._isMatching(b,a,c))return d=c,!0},this);return d},_isMatching:function(b,a,c){var d,e=!1,f=null,h=b.gxeData.nsUrisByPrefix,g;d=a;-1!==d.indexOf(":")&&(d=d.split(":"),g=d[0],d=d[1],g in h?f=h[g]:0===a.indexOf("xml:")&&(f="http://www.w3.org/XML/1998/namespace"));8>=n("ie")&&(f="");b=b.considerGML3andGML32;a=c.namespaceURI===f;!a&&b&&("http://www.opengis.net/gml/3.2"===
f?a="http://www.opengis.net/gml"===c.namespaceURI:"http://www.opengis.net/gml"===f&&(a="http://www.opengis.net/gml/3.2"===c.namespaceURI));a&&d===c.localName&&(e=!0);return e},_getDomNodeText:function(b){return k.getNodeText(b)},_getDomNodeTextValues:function(b,a,c){var d=[],e,f;g.forEach(a,function(a){e=null;c?(f=this._findMatchingSubTarget(b,c,a))&&(e=this._getDomNodeText(f)):e=this._getDomNodeText(a);null!=e&&d.push(e)},this);return d},_printGxeReferences:function(b){var a;for(a=0;a<b.depth;a++);
g.forEach(b.attributeRefs,function(a){});g.forEach(b.elementRefs,function(a){this._printGxeReferences(a)},this)},_repairChoices:function(b,a){var c=function(b,c){var f=[];g.forEach(a,function(a){var k=!0;g.forEach(a.childNodes,function(a){if(a.localName===c)if(k)k=!1;else{var g=document.createElement(b);g.appendChild(a.cloneNode(!0));f.push(g)}})});g.forEach(f,function(b){a.push(b)})};a&&0<a.length&&"attrdomv"===b.target&&c("attrdomv","edom")},_updateAttribute:function(b,a,c){if(!a.fixed){var d=this._findMatchingDomAttribute(b,
a.target,c);d&&(c=this._getDomNodeText(d),this._updateXNode(b,a,d,c))}},_updateElementText:function(b,a,c){if(!a.fixed){var d=this._getDomNodeText(c);this._updateXNode(b,a,c,d)}},_updateXNode:function(b,a,c,d){if(null!==d&&a.inputWidget){if(a.isDocumentTitle&&(b.gxeDocument.originalTitle=d,b.asTemplate))return;a.inputWidget.importValue({domNode:c,asTemplate:b.asTemplate},d);!a.hide&&a.toggleContent&&a.toggleContent(!0)}},_walk:function(b,a,c){if(!a.fixed){var d=!0,e=null,f,h;if(c)a._isGxeElement?
(e=this._findMatchingDomElements(b,a.target,c))||(d=!1):a._isGxeAttribute&&(d=!1,this._updateAttribute(b,a,c));else if(c=b.xmlDocument.documentElement,this._isMatching(b,a.target,c))e=[c];else throw Error("The XML root element does not match the editor definition.");e&&0<e.length&&(e=p.evaluateDomMatch(a,e,b.gxeData.nsPrefixesByUri))&&0<e.length&&this._repairChoices(a,e);var k=a.inputWidget&&a.inputWidget._supportsMultipleValues,l=a.multiplicityHeader;e&&0<e.length&&(a.toggleContent&&a.toggleContent(!0),
(f=a.getParent())&&f._isGxeElementChoice?f.ensureActiveTab(a):f&&((h=f.getParent())&&h._isGxeElementChoice?h.ensureActiveTab(f):h&&(f=h.getParent())&&f._isGxeElementChoice&&f.ensureActiveTab(h)),k?(d=!1,h=this._getDomNodeTextValues(b,e,a.inputWidget.subTarget),a.inputWidget.importValues({domNodes:e},h)):1===e.length?(c=e[0],this._updateElementText(b,a,c)):l?(c=e[0],this._updateElementText(b,a,e[0]),g.forEach(e,function(c,d){0<d&&!("unbounded"!==a.maxOccurs&&d===a.maxOccurs)&&l.repeatElement(a,!1).then(m.hitch(this,
function(a){a&&(this._updateElementText(b,a,c),g.forEach(a.getChildren(),function(a){this._walk(b,a,c)},this))}),function(a){console.error(a)})},this)):(c=e[0],this._updateElementText(b,a,c)));d&&g.forEach(a.getChildren(),function(a){this._walk(b,a,c)},this)}}});n("extend-esri")&&m.setObject("dijit.metadata.base.xml.XmlImporter",l,q);return l});