//>>built
define("esri/layers/rasterFormats/TiffDecoder",["./Jpg","./Zlib"],function(Ja,ca){var Ka=function(){var a=new ArrayBuffer(4),c=new Uint8Array(a),a=new Uint32Array(a);c[0]=1;c[1]=2;c[2]=3;c[3]=4;return 67305985===a[0]},bb=function(){var a=[];a[254]="NEWSUBFILETYPE";a[255]="SUBFILETYPE";a[256]="IMAGEWIDTH";a[257]="IMAGELENGTH";a[258]="BITSPERSAMPLE";a[259]="COMPRESSION";a[262]="PHOTOMETRICINTERPRETATION";a[263]="THRESHHOLDING";a[264]="CELLWIDTH";a[265]="CELLLENGTH";a[266]="FILLORDER";a[269]="DOCUMENTNAME";
a[270]="IMAGEDESCRIPTION";a[271]="MAKE";a[272]="MODEL";a[273]="STRIPOFFSETS";a[274]="ORIENTATION";a[277]="SAMPLESPERPIXEL";a[278]="ROWSPERSTRIP";a[279]="STRIPBYTECOUNTS";a[280]="MINSAMPLEVALUE";a[281]="MAXSAMPLEVALUE";a[282]="XRESOLUTION";a[283]="YRESOLUTION";a[284]="PLANARCONFIGURATION";a[285]="PAGENAME";a[286]="XPOSITION";a[287]="YPOSITION";a[288]="FREEOFFSETS";a[289]="FREEBYTECOUNTS";a[290]="GRAYRESPONSEUNIT";a[291]="GRAYRESPONSECURVE";a[292]="T4OPTIONS";a[293]="T6OPTIONS";a[296]="RESOLUTIONUNIT";
a[297]="PAGENUMBER";a[300]="COLORRESPONSEUNIT";a[301]="TRANSFERFUNCTION";a[305]="SOFTWARE";a[306]="DATETIME";a[315]="ARTIST";a[316]="HOSTCOMPUTER";a[317]="PREDICTOR";a[318]="WHITEPOINT";a[319]="PRIMARYCHROMATICITIES";a[320]="COLORMAP";a[321]="HALFTONEHINTS";a[322]="TILEWIDTH";a[323]="TILELENGTH";a[324]="TILEOFFSETS";a[325]="TILEBYTECOUNTS";a[326]="BADFAXLINES";a[327]="CLEANFAXDATA";a[328]="CONSECUTIVEBADFAXLINES";a[330]="SUBIFD";a[332]="INKSET";a[333]="INKNAMES";a[334]="NUMBEROFINKS";a[336]="DOTRANGE";
a[337]="TARGETPRINTER";a[338]="EXTRASAMPLES";a[339]="SAMPLEFORMAT";a[340]="SMINSAMPLEVALUE";a[341]="SMAXSAMPLEVALUE";a[342]="TRANSFERRANGE";a[347]="JPEGTABLES";a[512]="JPEGPROC";a[513]="JPEGIFOFFSET";a[514]="JPEGIFBYTECOUNT";a[515]="JPEGRESTARTINTERVAL";a[517]="JPEGLOSSLESSPREDICTORS";a[518]="JPEGPOINTTRANSFORM";a[519]="JPEGQTABLES";a[520]="JPEGDCTABLES";a[521]="JPEGACTABLES";a[529]="YCBCRCOEFFICIENTS";a[530]="YCBCRSUBSAMPLING";a[531]="YCBCRPOSITIONING";a[532]="REFERENCEBLACKWHITE";a[33550]="GEOPIXELSCALE";
a[33922]="GEOTIEPOINTS";a[33432]="COPYRIGHT";a[42112]="GDAL_METADATA";a[42113]="GDAL_NODATA";a[50844]="RPCCOEFFICIENT";a[34735]="GEOKEYDIRECTORY";a[34736]="GEODOUBLEPARAMS";a[34737]="GEOASCIIPARAMS";return a}(),La=[0,1,1,2,4,8,1,1,2,4,8,4,8],Ma=function(a,c){var r="UNKNOWN";3===a?r="F32":1===a?8>=c?r="U8":16>=c?r="U16":32>=c&&(r="U32"):2===a&&(8>=c?r="S8":16>=c?r="S16":32>=c&&(r="S32"));return r};return{decode:function(a){var c,r=new DataView(a,0,8),Na=r.getUint16(0,!1),S;if(18761===Na)S=!0;else if(19789===
Na)S=!1;else throw"unexpected endianess byte";if(42!==r.getUint16(2,S))throw"unexpected tiff identifier";var cb=r.getUint32(4,S);c=S;var T,ra,U,sa,V,da,W,Oa,Pa,ta,X;T=cb;for(var ua=[];T;){ra=(new DataView(a,T,2)).getUint16(0,c);U=T+2;T=(new DataView(a,U+12*ra,4)).getUint32(0,c);ta={};for(sa=0;sa<ra;sa++)if(V=new DataView(a,U,12),da=V.getUint16(0,c),W=V.getUint16(2,c),Oa=V.getUint32(4,c),Pa=V.getUint32(8,c),U+=12,!(7===W||12<W)){var db=X={fieldTag:da,fieldType:W,fieldValueCount:Oa,fieldValueOffset:Pa},
q=a,t=c,M=[],ea=X.fieldType,fa=X.fieldValueCount,N=X.fieldValueOffset,m=N,va=La[ea],Qa=8*va,eb=fa*va,Ra=8*fa*La[ea],n=void 0,B=void 0;if(32>=Ra)if(t||(N>>>=32-Ra),1===fa)M=[N];else for(B=0;B<fa;B++)M.push(N<<Qa*B>>>32-Qa);else for(m=N;m<N+eb;m+=va){switch(ea){case 1:n=(new DataView(q,m,1)).getUint8(0);break;case 2:n=(new DataView(q,m,1)).getUint8(0);break;case 3:n=(new DataView(q,m,2)).getUint16(0,t);break;case 4:n=(new DataView(q,m,4)).getUint32(0,t);break;case 5:n=(new DataView(q,m,4)).getUint32(0,
t)/(new DataView(q,m+4,4)).getUint32(0,t);break;case 6:n=(new DataView(q,m,1)).getInt8(0);break;case 8:n=(new DataView(q,m,2)).getInt16(0,t);break;case 9:n=(new DataView(q,m,4)).getInt32(0,t);break;case 10:n=(new DataView(q,m,4)).getInt32(0,t)/(new DataView(q,m+4,4)).getInt32(0,t);break;case 11:n=(new DataView(q,m,4)).getFloat32(0,t);break;case 12:n=(new DataView(q,m,8)).getFloat64(0,t);break;case 7:n=null;break;default:n=null}M.push(n)}if(2===ea)for(var ga="",wa=M,M=[],B=0;B<wa.length;B++)0===wa[B]?
(M.push(ga),ga=""):ga+=String.fromCharCode(wa[B]);db.fieldValues=M;var fb=ta,xa=bb[da];void 0===xa&&(xa="unknown"+da);fb[xa]={type:W,values:X.fieldValues}}ua.push(ta)}if(0===ua.length)throw"no valid image file directory";var u,g,b=ua[0],O=void 0===b.GDAL_NODATA||null===b.GDAL_NODATA?null:parseFloat(b.GDAL_NODATA.values[0]);if(b.TILEOFFSETS){var Sa,x,C,gb=Ka()===c,F=b.TILEOFFSETS?b.TILEOFFSETS.values:void 0;if(void 0===F)g=void 0;else{var P=b.TILEBYTECOUNTS.values,ha=b.TILEWIDTH.values[0],Ta=b.TILELENGTH.values[0],
Q=b.IMAGEWIDTH.values[0],ya=b.IMAGELENGTH.values[0],D=Q*ya,G=b.BITSPERSAMPLE.values[0],p=b.SAMPLESPERPIXEL.values[0],Y=b.SAMPLEFORMAT?b.SAMPLEFORMAT.values[0]:1,ia=Ma(Y,G);if(1!==(b.PLANARCONFIGURATION?b.PLANARCONFIGURATION.values[0]:1))throw"can only handle PLANARCONFIGURATION\x3d1";var v=b.COMPRESSION?b.COMPRESSION.values[0]:1;if(!(1===v||6===v||8===v||32946===v))throw"this compression is not supported at this moment";if(3<Y)g=void 0;else{3===Y?(x=new Float32Array(D*p),C=Float32Array):1===Y?8>=
G?(x=new Uint8Array(D*p),C=Uint8Array):16>=G?(x=new Uint16Array(D*p),C=Uint16Array):32>=G&&(x=new Uint32Array(D*p),C=Uint32Array):2===Y&&(8>=G?(x=new Int8Array(D*p),C=Int8Array):16>=G?(x=new Int16Array(D*p),C=Int16Array):32>=G&&(x=new Int32Array(D*p),C=Int32Array));var d,Z,h,$,za,Aa,Ba,Ua,Ca,Da,Va,Wa,y,e,H,Ea,ja,Fa,Xa=Math.ceil(Q/ha);if(0===G%8)for(d=0;d<F.length;d++){Aa=Math.floor(d/Xa)*Ta;Ba=d%Xa*ha;Ua=(Aa*Q+Ba)*p;if("U8"===ia||"S8"===ia||gb)if(8===v||32946===v)e=new Uint8Array(a,F[d],P[d]),ja=
new ca(e),Fa=ja.getBytes(),y=new ArrayBuffer(Fa.length),e=new Uint8Array(y),e.set(Fa);else if(6===v){e=new Uint8Array(a,F[d],P[d]);var ka=new Ja;ka.parse(e);var Ya=ka.getData(ka.width,ka.height);y=new ArrayBuffer(Ya.length);e=new Uint8Array(y);e.set(Ya)}else 1===v&&(y=a.slice(F[d],F[d]+P[d]));else switch(8===v||32946===v?(e=new Uint8Array(a,F[d],P[d]),ja=new ca(e),e=ja.getBytes(),y=new ArrayBuffer(e.length),H=new Uint8Array(y)):1===v&&(y=new ArrayBuffer(P[d]),e=new Uint8Array(a,F[d],P[d]),H=new Uint8Array(y)),
ia){case "U16":case "S16":for(h=0;h<e.length;h+=2)H[h]=e[h+1],H[h+1]=e[h];break;case "U32":case "S32":case "F32":for(h=0;h<e.length;h+=4)H[h]=e[h+3],H[h+1]=e[h+2],H[h+2]=e[h+1],H[h+3]=e[h]}Sa=new C(y);Wa=Math.min(ha,Q-Ba);Va=Math.min(Ta,ya-Aa);for($=0;$<Va;$++){Ca=Ua+$*Q*p;Da=$*ha*p;for(za=0;za<Wa*p;za++,Ca++,Da++)x[Ca]=Sa[Da]}}var la={width:Q,height:ya,pixelType:ia};if(1===p)la.pixels=[x];else{la.pixels=[];for(d=0;d<p;d++){Ea=new C(D);for(Z=0;Z<D;Z++)Ea[Z]=x[Z*p+d];la.pixels.push(Ea)}}g=la}}}else if(b.STRIPOFFSETS){var Za,
z,E,hb=Ka()===c,I=b.STRIPOFFSETS?b.STRIPOFFSETS.values:void 0;if(void 0===I)g=void 0;else{var R=b.STRIPBYTECOUNTS.values,ib=b.ROWSPERSTRIP.values,ma=b.IMAGEWIDTH.values[0],Ga=b.IMAGELENGTH.values[0],J=ma*Ga,K=b.BITSPERSAMPLE.values[0],w=b.SAMPLESPERPIXEL.values[0],aa=b.SAMPLEFORMAT?b.SAMPLEFORMAT.values[0]:1,na=Ma(aa,K);if(1!==(b.PLANARCONFIGURATION?b.PLANARCONFIGURATION.values[0]:1))throw"can only handle PLANARCONFIGURATION\x3d1";var s=b.COMPRESSION?b.COMPRESSION.values[0]:1;if(!(1===s||6===s||8===
s||32946===s))throw"compressed tiff is not supported at this moment";if(3<aa)g=void 0;else{3===aa?(z=new Float32Array(J*w),E=Float32Array):1===aa?8>=K?(z=new Uint8Array(J*w),E=Uint8Array):16>=K?(z=new Uint16Array(J*w),E=Uint16Array):32>=K&&(z=new Uint32Array(J*w),E=Uint32Array):2===aa&&(8>=K?(z=new Int8Array(J*w),E=Int8Array):16>=K?(z=new Int16Array(J*w),E=Int16Array):32>=K&&(z=new Int32Array(ma*Ga*w),E=Int32Array));var k,ba,l,$a,A,f,L,Ha,oa,Ia;if(0===K%8)for(k=0;k<I.length;k++){$a=k*(ib*ma)*w;if("U8"===
na||"S8"===na||hb)if(8===s||32946===s)f=new Uint8Array(a,I[k],R[k]),oa=new ca(f),Ia=oa.getBytes(),A=new ArrayBuffer(Ia.length),f=new Uint8Array(A),f.set(Ia);else if(6===s){f=new Uint8Array(a,I[k],R[k]);var pa=new Ja;pa.parse(f);var ab=pa.getData(pa.width,pa.height);A=new ArrayBuffer(ab.length);f=new Uint8Array(A);f.set(ab)}else 1===s&&(A=a.slice(I[k],I[k]+R[k]));else switch(6===s||8===s||32946===s?(f=new Uint8Array(a,I[k],R[k]),oa=new ca(f),f=oa.getBytes(),A=new ArrayBuffer(f.length),L=new Uint8Array(A)):
1===s&&(A=new ArrayBuffer(R[k]),f=new Uint8Array(a,I[k],R[k]),L=new Uint8Array(A)),na){case "U16":case "S16":for(l=0;l<f.length;l+=2)L[l]=f[l+1],L[l+1]=f[l];break;case "U32":case "S32":case "F32":for(l=0;l<f.length;l+=4)L[l]=f[l+3],L[l+1]=f[l+2],L[l+2]=f[l+1],L[l+3]=f[l]}Za=new E(A);z.set(Za,$a)}var qa={width:ma,height:Ga,pixelType:na};if(1===w)qa.pixels=[z];else{qa.pixels=[];for(k=0;k<w;k++){Ha=new E(J);for(ba=0;ba<J;ba++)Ha[ba]=z[ba*w+k];qa.pixels.push(Ha)}}g=qa}}}if(null!==O){g.maskData=new Uint8Array(g.width*
g.height);if(1E24<Math.abs(O))for(u=0;u<g.width*g.height;u++)1E-6>Math.abs((g.pixels[0][u]-O)/O)?g.maskData[u]=0:g.maskData[u]=1;else for(u=0;u<g.width*g.height;u++)g.maskData[u]=g.pixels[0][u]===O?0:1;g.noDataValue=O}return g}}});